// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from 'dotenv';
import 'dotenv/config';
import { resolve } from 'path';
import { defineConfig } from 'prisma/config';

const env = process.env.NODE_ENV || 'development';

// 根据环境动态加载对应的 .env 文件（如 .env.development, .env.production）
config({ path: resolve(process.cwd(), `.env.${env}`) });

console.log('当前加载环境:', env);

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'] || '',
  },
});
